[package]
name = "inspirv-builder"
version = "0.1.0"
authors = ["msiglreith <msiglreith@users.noreply.github.com>"]

[dependencies]
inspirv = { path = "../inspirv", version = "0.1.0" }
linked-hash-map = "0.2.1"

[[example]]
name = "export"
path = "example/main.rs"
